
CREATE TABLE "TB_FREEBOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"ART_WRITER"	VARCHAR2(30)		NULL,
	"IP_ADDRESS"	VARCHAR2(50)		NULL,
	"ART_TITLE"	VARCHAR2(30)		NULL,
	"ART_PASSWORD"	VARCHAR2(10)		NULL,
	"ART_CONTENT"	VARCHAR2(4000)		NULL,
	"COUNT"	NUMBER		NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL
);

COMMENT ON COLUMN "TB_FREEBOARD"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "TB_FREEBOARD"."CATEGORY_NO" IS '카테고리';

COMMENT ON COLUMN "TB_FREEBOARD"."ART_WRITER" IS '닉네임';

COMMENT ON COLUMN "TB_FREEBOARD"."IP_ADDRESS" IS '작성자 IP 주소';

COMMENT ON COLUMN "TB_FREEBOARD"."ART_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "TB_FREEBOARD"."ART_PASSWORD" IS '게시글 비밀번호';

COMMENT ON COLUMN "TB_FREEBOARD"."ART_CONTENT" IS '게시글 내용'; 

COMMENT ON COLUMN "TB_FREEBOARD"."COUNT" IS '조회수';

COMMENT ON COLUMN "TB_FREEBOARD"."CREATE_DATE" IS '작성일';

COMMENT ON COLUMN "TB_FREEBOARD"."STATUS" IS '상태값';

ALTER TABLE "TB_FREEBOARD" ADD CONSTRAINT "PK_TB_FREEBOARD" PRIMARY KEY (
	"BOARD_NO"
);

CREATE TABLE "BOARD_CATEGORY" (
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_CATEGORY"."CATEGORY_NO" IS '카테고리';

ALTER TABLE "BOARD_CATEGORY" ADD CONSTRAINT "PK_BOARD_CATEGORY" PRIMARY KEY (
	"CATEGORY_NO"
);







CREATE TABLE "TB_ITEMBOARD" (
	"BOARD_NO"	NUMBER PRIMARY KEY,
	"MEM_NO"	NUMBER		NOT NULL,
	"IBOARD_TITLE"	VARCHAR2(100)		NOT NULL,
	"IBOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"IBOARD_POST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"IBOARD_MODIFY_DATE"	DATE		NOT NULL,
	"COUNT"	NUMBER DEFAULT 0 NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	CHECK (STATUS IN('Y','N','C'))
);

COMMENT ON COLUMN "TB_ITEMBOARD"."BOARD_NO" IS '게시글 번호 (PK)';

COMMENT ON COLUMN "TB_ITEMBOARD"."MEM_NO" IS '회원번호(FK)';

COMMENT ON COLUMN "TB_ITEMBOARD"."STATUS" IS '상태값 Y(활성),N(삭제),C (거래완료)';



CREATE TABLE "TB_SCRAP" (
    "SCRAP_NO" NUMBER PRIMARY KEY,
	"MEM_NO"	NUMBER REFERENCES TB_MEMBER,
	"IBOARD_NO"	NUMBER REFERENCES TB_ITEMBOARD,
	"CREATE_DATE"	DATE NOT NULL,
    "STATUS" VARCHAR2(10) DEFAULT 'Y' CHECK (STATUS IN('Y','N'))
);

COMMENT ON COLUMN "TB_SCRAP"."SCRAP_NO" IS '스크랩 번호';
COMMENT ON COLUMN "TB_SCRAP"."MEM_NO" IS '회원번호';
COMMENT ON COLUMN "TB_SCRAP"."IBOARD_NO" IS '참조 중고거래 게시 번호';
COMMENT ON COLUMN "TB_SCRAP"."CREATE_DATE" IS '찜한날짜';


CREATE TABLE "TB_REVIEW" (
	"REVIEW_NO"	NUMBER PRIMARY KEY,
	"MEM_NO"	NUMBER REFERENCES TB_MEMBER,
	"BOARD_NO"	NUMBER REFERENCES TB_ITEMBOARD,
	"REVIEW_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"RATING"	NUMBER CHECK (RATING BETWEEN 1 AND 5),
    "STATUS" VARCHAR2(10) DEFAULT 'Y' CHECK (STATUS IN('Y','N')) 
);

COMMENT ON COLUMN "TB_REVIEW"."REVIEW_NO" IS '후기번호';

COMMENT ON COLUMN "TB_REVIEW"."MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_REVIEW"."BOARD_NO" IS '참고 게시글번호';

COMMENT ON COLUMN "TB_REVIEW"."REVIEW_CONTENT" IS '후기내용';

COMMENT ON COLUMN "TB_REVIEW"."RATING" IS '별점 1~5';

CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER PRIMARY KEY,
	"CATEGORY_NO"	NUMBER REFERENCES BOARD_CATEGORY,
	"REF_BNO"	NUMBER		NULL,
	"MEM_NO"	NUMBER REFERENCES TB_MEMBER,
	"REPLY_CONTENT"	VARCHAR2(400) NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y','N'))
);

COMMENT ON COLUMN "REPLY"."CATEGORY_NO" IS '카테고리';

COMMENT ON COLUMN "REPLY"."MEM_NO" IS '회원번호(PK)';


CREATE TABLE "JOB_BOARD" (
	"JBOARD_NO"	NUMBER PRIMARY KEY,
	"CATEGORY_NO"	NUMBER REFERENCES BOARD_CATEGORY,
	"JBOARD_TITLE"	VARCHAR2(100)		NOT NULL,
	"JOB_DESCRIPTION"	VARCHAR2(4000)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"SALARY"	NUMBER		NOT NULL,
	"DURATION"	VARCHAR2(50)		NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	CHECK(STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN "JOB_BOARD"."JBOARD_NO" IS '일손찾기 PK';

COMMENT ON COLUMN "JOB_BOARD"."CATEGORY_NO" IS '카테고리 번호';

COMMENT ON COLUMN "JOB_BOARD"."JBOARD_TITLE" IS '제목';

COMMENT ON COLUMN "JOB_BOARD"."JOB_DESCRIPTION" IS '내용';

COMMENT ON COLUMN "JOB_BOARD"."CREATE_DATE" IS '작성일';

COMMENT ON COLUMN "JOB_BOARD"."MODIFY_DATE" IS '수정일';

COMMENT ON COLUMN "JOB_BOARD"."SALARY" IS '급여';

COMMENT ON COLUMN "JOB_BOARD"."DURATION" IS '기간';

COMMENT ON COLUMN "JOB_BOARD"."STATUS" IS '상태값 Y,N';


CREATE TABLE "TB_APPLY" (
    "APPLY_NO" NUMBER PRIMARY KEY,
	"REF_BNO"	NUMBER REFERENCES JOB_BOARD,
	"APPLY_WRITER"	NUMBER REFERENCES TB_MEMBER,
	"APPLY_CONTENT"	VARCHAR2(2000)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y' CHECK(STATUS IN('Y','N'))
);

COMMENT ON COLUMN "TB_APPLY"."APPLY_WRITER" IS '지원자 회원번호';

COMMENT ON COLUMN "TB_APPLY"."REF_BNO" IS '참조 게시글번호';

COMMENT ON COLUMN "TB_APPLY"."APPLY_CONTENT" IS '지원 내용';

COMMENT ON COLUMN "TB_APPLY"."CREATE_DATE" IS '작성일';

COMMENT ON COLUMN "TB_APPLY"."STATUS" IS '상태값';

COMMENT ON COLUMN "TB_APPLY"."APPLY_NO" IS '지원서 번호';

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


CREATE TABLE "TB_GALLERY" (
	"GALLERY_NO"	NUMBER PRIMARY KEY,
	"MEM_NO"	NUMBER REFERENCES TB_MEMBER,
	"CATEGORY_NO"	NUMBER REFERENCES BOARD_CATEGORY
);

COMMENT ON COLUMN "TB_GALLERY"."MEM_NO" IS '회원번호(PK)';

COMMENT ON COLUMN "TB_GALLERY"."CATEGORY_NO" IS '카테고리';

CREATE TABLE "JOB_BOARD" (
	"JBOARD_NO"	NUMBER		NOT NULL,
	"JBOARD_WRITER"	NUMBER		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"JBOARD_TITLE"	VARCHAR2(100)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"SALARY"	NUMBER		NOT NULL,
	"DURATION"	VARCHAR2(50)		NULL,
	"JOB_DESCRIPTION"	VARCHAR2(4000)		NOT NULL,
	"STATUS"	VARCHAR2(1) DEFAULT'Y'	NOT NULL
);

COMMENT ON COLUMN "JOB_BOARD"."CATEGORY_NO" IS '카테고리';

COMMENT ON COLUMN "JOB_BOARD"."STATUS" IS '상태값 Y,N';


CREATE TABLE "TB_MESSAGE" (
	"MSG_NO"	NUMBER		NOT NULL,
	"MSG_SENDER"	VARCHAR2(20)		NOT NULL,
	"MSG_RECEIVER"	VARCHAR2(20)		NOT NULL,
	"MSG_TITLE"	VARCHAR2(30)		NULL,
	"MSG_TEXT"	VARCHAR2(400)		NULL,
	"DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "TB_MESSAGE"."MSG_NO" IS '쪽지번호(PK)';

COMMENT ON COLUMN "TB_MESSAGE"."MSG_SENDER" IS '회원번호(PK)/보내는 사람(나)';

COMMENT ON COLUMN "TB_MESSAGE"."MSG_RECEIVER" IS '회원번호(PK)/받는사람(ID로 검색되게)';

COMMENT ON COLUMN "TB_MESSAGE"."MSG_TITLE" IS '쪽지제목';

COMMENT ON COLUMN "TB_MESSAGE"."MSG_TEXT" IS '쪽지내용';

COMMENT ON COLUMN "TB_MESSAGE"."DATE" IS '쪽지 수신/발신 날짜';





CREATE TABLE "TB_APPLY" (
	"APPLY_WRITER"	NUMBER		NOT NULL,
	"APPLY_CONTENT"	VARCHAR2(2000)		NOT NULL,
	"JBOARD_NO"	NUMBER		NOT NULL,
	"JBOARD_WRITER"	NUMBER		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "TB_APPLY"."CATEGORY_NO" IS '카테고리';

CREATE TABLE "ATTACHMENT" (
	"FILE_NO"	NUMBER PRIMARY KEY,
	"CATEGORY_NO"	NUMBER REFERENCES BOARD_CATEGORY,
	"REF_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
	"MODIFIED_NAME"	VARCHAR2(255)		NULL,
	"SAVE_PATH"	VARCHAR2(1000)		NOT NULL,
	"UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	CHECK (STATUS IN('Y','N'))
);

COMMENT ON COLUMN ATTACHMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN "ATTACHMENT"."CATEGORY_NO" IS '카테고리';
COMMENT ON COLUMN ATTACHMENT.REF_NO IS '참조 게시글번호';
COMMENT ON COLUMN ATTACHMENT.ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN ATTACHMENT.MODIFIED_NAME IS '파일수정명';
COMMENT ON COLUMN ATTACHMENT.SAVE_PATH IS '저장경로';
COMMENT ON COLUMN ATTACHMENT.UPLOAD_DATE IS '업로드일';
COMMENT ON COLUMN "ATTACHMENT"."STATUS" IS '상태값 Y/N';

ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "PK_ATTACHMENT" PRIMARY KEY (
	"FILE_NO"
);


CREATE TABLE "FB_REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"REF_BNO"	NUMBER		NOT NULL,
	"WRITER"	VARCHAR2(30)		NULL,
	"IP_ADDRESS"	VARCHAR2(50)		NULL,
	"REPLY_CONTENT"	VARCHAR2(400)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN "FB_REPLY"."REF_BNO" IS '게시글 번호';

ALTER TABLE "FB_REPLY" ADD CONSTRAINT "PK_FB_REPLY" PRIMARY KEY (
	"REPLY_NO"
);



-------------------------------------------------------------------------------


ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_NO"
);



ALTER TABLE "TB_SCRAP" ADD CONSTRAINT "PK_TB_SCRAP" PRIMARY KEY (
	"MEM_NO",
	"IBOARD_NO"
);



ALTER TABLE "TB_GALLERY" ADD CONSTRAINT "PK_TB_GALLERY" PRIMARY KEY (
	"GALLERY_NO"
);

ALTER TABLE "JOB_BOARD" ADD CONSTRAINT "PK_JOB_BOARD" PRIMARY KEY (
	"JBOARD_NO"
);

ALTER TABLE "RESTAURANT" ADD CONSTRAINT "PK_RESTAURANT" PRIMARY KEY (
	"RESTAURANT_NO"
);


ALTER TABLE "TB_MESSAGE" ADD CONSTRAINT "PK_TB_MESSAGE" PRIMARY KEY (
	"MSG_NO"
);

ALTER TABLE "JBOARD_NOTICE" ADD CONSTRAINT "PK_JBOARD_NOTICE" PRIMARY KEY (
	"JNOTICE_NO",
	"JNOTICE_WRITER"
);

ALTER TABLE "TB_NOTICE" ADD CONSTRAINT "PK_TB_NOTICE" PRIMARY KEY (
	"NOTICE_NO",
	"CATEGORY_NO"
);



ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "TB_APPLY" ADD CONSTRAINT "PK_TB_APPLY" PRIMARY KEY (
	"APPLY_WRITER"
);










ALTER TABLE "TB_SCRAP" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_SCRAP_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
);

ALTER TABLE "TB_SCRAP" ADD CONSTRAINT "FK_TB_ITEMBOARD_TO_TB_SCRAP_1" FOREIGN KEY (
	"IBOARD_NO"
)
REFERENCES "TB_ITEMBOARD" (
	"BOARD_NO"
);

ALTER TABLE "JOB_BOARD" ADD CONSTRAINT "FK_BOARD_CATEGORY_TO_JOB_BOARD_1" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "BOARD_CATEGORY" (
	"CATEGORY_NO"
);

ALTER TABLE "TB_NOTICE" ADD CONSTRAINT "FK_BOARD_CATEGORY_TO_TB_NOTICE_1" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "BOARD_CATEGORY" (
	"CATEGORY_NO"
);

COMMIT;
ALTER TABLE TB_FREEBOARD DROP CONSTRAINT SYS_C007276;
ALTER TABLE TB_MEMBER DROP CONSTRAINT SYS_C007240;
ALTER TABLE TB_FREEBOARD ADD CHECK (STATUS IN('Y','N'));

INSERT INTO BOARD_CATEGORY VALUES (10, '자유게시판');
INSERT INTO BOARD_CATEGORY VALUES (20, '중고거래');
INSERT INTO BOARD_CATEGORY VALUES (30, '일손찾기');


--FOREIGN KEY--
ALTER TABLE TB_ITEMBOARD ADD CONSTRAINT FK_TB_ITEMBOARD FOREIGN KEY (MEM_NO) REFERENCES TB_MEMBER;
ALTER TABLE ATTACHMENT ADD CONSTRAINT ATT_FK_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES BOARD_CATEGORY;
ALTER TABLE TB_NOTICE ADD PRIMARY KEY (NOTICE_NO);
ALTER TABLE TB_NOTICE ADD CONSTRAINT NOTICE_FK_CATEGORY_NO FOREIGN KEY (CATEGORY_NO) REFERENCES BOARD_CATEGORY;
ALTER TABLE TB_FREEBOARD ADD CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES BOARD_CATEGORY;
ALTER TABLE FB_REPLY ADD CONSTRAINT FK_REF_BNO FOREIGN KEY (REF_BNO) REFERENCES TB_FREEBOARD; 


ALTER TABLE FB_REPLY DROP CONSTRAINT FK_REF_BNO;
